2014/03/14 16:04:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "mods".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('mods')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('mods')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/mods')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii\asdf\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/asdf/index.php?r=site/mods
---
2014/03/14 16:04:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "mods".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('mods')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('mods')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/mods/index')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii\asdf\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/asdf/index.php?r=site/mods/index
---
2014/03/14 16:04:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "mods".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('mods')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('mods')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/mods')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii\asdf\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/asdf/index.php?r=site/mods
---
2014/03/14 16:06:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "yii".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('yii')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\asdf\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/asdf/index.php?r=yii
---
2014/03/14 16:06:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "yii/mods".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('yii/mods')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\asdf\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/asdf/index.php?r=yii/mods
---
2014/03/14 16:06:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "yii/mods/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('yii/mods/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\asdf\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/asdf/index.php?r=yii/mods/index
---
2014/03/21 15:15:39 [warning] [application] Failed to set unsafe attribute "regdate" of "CrugeStoredUser".
in C:\xampp\htdocs\yii\asdf\protected\modules\cruge\models\data\CrugeStoredUser.php (134)
in C:\xampp\htdocs\yii\asdf\protected\modules\cruge\controllers\UiController.php (240)
in C:\xampp\htdocs\yii\asdf\protected\modules\cruge\controllers\UiController.php (230)
2014/03/21 15:15:39 [warning] [application] Failed to set unsafe attribute "actdate" of "CrugeStoredUser".
in C:\xampp\htdocs\yii\asdf\protected\modules\cruge\models\data\CrugeStoredUser.php (134)
in C:\xampp\htdocs\yii\asdf\protected\modules\cruge\controllers\UiController.php (240)
in C:\xampp\htdocs\yii\asdf\protected\modules\cruge\controllers\UiController.php (230)
2014/03/21 15:15:39 [warning] [application] Failed to set unsafe attribute "logondate" of "CrugeStoredUser".
in C:\xampp\htdocs\yii\asdf\protected\modules\cruge\models\data\CrugeStoredUser.php (134)
in C:\xampp\htdocs\yii\asdf\protected\modules\cruge\controllers\UiController.php (240)
in C:\xampp\htdocs\yii\asdf\protected\modules\cruge\controllers\UiController.php (230)
2014/03/21 15:19:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\asdf\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/asdf/index.php?r=gii
---
2014/03/21 15:28:35 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'asdf.persona' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `Persona`.
in C:\xampp\htdocs\yii\asdf\index.php (13)
2014/03/21 15:42:29 [error] [exception.CException] exception 'CException' with message 'Alias "appication.models.Post" is invalid. Make sure it points to an existing directory or file.' in C:\xampp\htdocs\yii\framework\YiiBase.php:347
Stack trace:
#0 C:\xampp\htdocs\yii\framework\gii\generators\crud\CrudCode.php(59): YiiBase::import('appication.mode...', true)
#1 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): CrudCode->validateModel('model', Array)
#2 C:\xampp\htdocs\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(CrudCode), 'model')
#3 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(CrudCode), NULL)
#4 C:\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(159): CModel->validate()
#5 C:\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#6 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\yii\asdf\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/yii/asdf/index.php?r=gii/crud/index
HTTP_REFERER=http://localhost/yii/asdf/index.php?r=gii/crud/index
---
2014/03/28 03:02:00 [error] [exception.CrugeException.500] Por favor cambie las referencias a 'UserIdentity' por 'CrugeUser'<br/>500
REQUEST_URI=/yii/asdf/index.php?r=site/login
HTTP_REFERER=http://localhost/yii/asdf/index.php?r=site/login
---
2014/04/20 20:04:40 [error] [exception.CDbException] SQLSTATE[08006] [7] FATAL:  la autentificación password falló para el usuario «grupo88»
2014/04/20 20:04:40 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:388
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1428): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1484): CActiveRecord->getTableAlias(true)
#7 C:\xampp\htdocs\yii\practica\protected\modules\cruge\models\data\CrugeSession.php(90): CActiveRecord->findByPk('0')
#8 C:\xampp\htdocs\yii\practica\protected\modules\cruge\components\CrugeFactory.php(46): CrugeSession::loadModel('0')
#9 C:\xampp\htdocs\yii\practica\protected\modules\cruge\components\CrugeUserManager.php(412): CrugeFactory->getICrugeSession('0')
#10 C:\xampp\htdocs\yii\practica\protected\modules\cruge\components\CrugeWebUser.php(451): CrugeUserManager->loadSession('0')
#11 C:\xampp\htdocs\yii\practica\protected\modules\cruge\components\CrugeWebUser.php(229): CrugeWebUser->getICrugeSession()
#12 C:\xampp\htdocs\yii\practica\protected\modules\cruge\components\CrugeWebUser.php(242): CrugeWebUser->getId()
#13 C:\xampp\htdocs\yii\framework\web\auth\CWebUser.php(200): CrugeWebUser->getIsGuest()
#14 C:\xampp\htdocs\yii\practica\protected\modules\cruge\components\CrugeWebUser.php(45): CWebUser->init()
#15 C:\xampp\htdocs\yii\framework\base\CModule.php(387): CrugeWebUser->init()
#16 C:\xampp\htdocs\yii\framework\base\CModule.php(103): CModule->getComponent('user')
#17 C:\xampp\htdocs\yii\practica\protected\views\layouts\main.php(36): CModule->__get('user')
#18 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#19 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#20 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#21 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#22 C:\xampp\htdocs\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#23 C:\xampp\htdocs\yii\framework\web\CBaseController.php(206): COutputProcessor->run()
#24 C:\xampp\htdocs\yii\framework\web\CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#25 C:\xampp\htdocs\yii\practica\protected\views\layouts\column1.php(6): CBaseController->endContent()
#26 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#27 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#28 C:\xampp\htdocs\yii\framework\web\CController.php(784): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#29 C:\xampp\htdocs\yii\practica\protected\controllers\SiteController.php(32): CController->render('index')
#30 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#31 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#32 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#33 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#34 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#35 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#36 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#37 C:\xampp\htdocs\yii\practica\index.php(13): CApplication->run()
#38 {main}
REQUEST_URI=/yii/practica/index.php
---
2014/04/20 20:04:40 [error] [exception.CDbException] SQLSTATE[08006] [7] FATAL:  la autentificación password falló para el usuario «grupo88»
2014/04/20 20:33:16 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23503]: Foreign key violation: 7 ERROR:  inserciÃ³n o actualizaciÃ³n en la tabla Â«evaluacionÂ» viola la llave forÃ¡nea Â«fk_evaluaci_corregir_supervisÂ»
DETAIL:  La llave (su_rut)=(16818192-2) no estÃ¡ presente en la tabla Â«supervisorÂ».. The SQL statement executed was: INSERT INTO "evaluacion" ("ev_id", "su_rut", "pra_id", "ev_asistencia", "ev_comportamiento", "ev_responsabilidad", "ev_capacidad", "ev_calidad", "ev_estructuracion", "ev_conocimientos", "ev_innovacion", "ev_producto", "ev_fortalezas", "ev_debilidades") VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9, :yp10, :yp11, :yp12, :yp13).
2014/04/20 20:33:16 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23503]: Foreign key violation: 7 ERROR:  inserciÃ³n o actualizaciÃ³n en la tabla Â«evaluacionÂ» viola la llave forÃ¡nea Â«fk_evaluaci_corregir_supervisÂ»
DETAIL:  La llave (su_rut)=(16818192-2) no estÃ¡ presente en la tabla Â«supervisorÂ».' in C:\xampp\htdocs\yii\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1077): CDbCommand->execute()
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(806): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\yii\practica\protected\controllers\EvaluacionController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): EvaluacionController->actionCreate()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('evaluacion/crea...')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yii\practica\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/practica/index.php?r=evaluacion/create
HTTP_REFERER=http://localhost/yii/practica/index.php?r=evaluacion/create
---
2014/04/20 20:37:37 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23503]: Foreign key violation: 7 ERROR:  inserciÃ³n o actualizaciÃ³n en la tabla Â«alumnoÂ» viola la llave forÃ¡nea Â«fk_alumno_pertenece_carreraÂ»
DETAIL:  La llave (ca_id)=(1) no estÃ¡ presente en la tabla Â«carreraÂ».. The SQL statement executed was: INSERT INTO "alumno" ("al_rut", "ca_id", "al_nombres", "al_apellidos", "al_correo", "al_telefono", "al_direccion") VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6).
2014/04/20 20:37:37 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23503]: Foreign key violation: 7 ERROR:  inserciÃ³n o actualizaciÃ³n en la tabla Â«alumnoÂ» viola la llave forÃ¡nea Â«fk_alumno_pertenece_carreraÂ»
DETAIL:  La llave (ca_id)=(1) no estÃ¡ presente en la tabla Â«carreraÂ».' in C:\xampp\htdocs\yii\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1077): CDbCommand->execute()
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(806): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\yii\practica\protected\controllers\AlumnoController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): AlumnoController->actionCreate()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('alumno/create')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yii\practica\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/practica/index.php?r=alumno/create
HTTP_REFERER=http://localhost/yii/practica/index.php?r=alumno/create
---
2014/04/20 20:39:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\yii\practica\protected\controllers\AlumnoController.php:157
Stack trace:
#0 C:\xampp\htdocs\yii\practica\protected\controllers\AlumnoController.php(55): AlumnoController->loadModel('01')
#1 [internal function]: AlumnoController->actionView('01')
#2 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(AlumnoController), Array)
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(AlumnoController), Object(ReflectionMethod), Array)
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('view')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('alumno/view')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yii\practica\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/practica/index.php?r=alumno/view&id=01
---
2014/04/20 20:45:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "secretaria/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('secretaria/inde...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\practica\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/practica/index.php?r=secretaria/index
---
2014/04/20 20:45:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "secretaria".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('secretaria')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\practica\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/practica/index.php?r=secretaria
---
2014/04/20 20:51:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "encargado".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('encargado')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\practica\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/practica/index.php?r=encargado
---
2014/04/20 20:51:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "Ecargado".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('Ecargado')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\practica\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/practica/index.php?r=Ecargado
---
2014/04/20 20:51:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "encargado".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('encargado')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\practica\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/practica/index.php?r=encargado
---
